# For more info, please check out: https://github.com/marketplace/actions/android-emulator-runner

name: CI

on: [push]

jobs:
  test:
    runs-on: macOS-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Sdl Android Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 29
        arch: x86_64
        headless: true
        disable-animations: true
        script: ./android/gradlew -p ./android :sdl_android:connectedCheck

    - name: Hello Sdl Android Tests
      uses: reactivecircus/android-emulator-runner@v1
      with:
        api-level: 29
        arch: x86_64
        headless: true
        disable-animations: true
        script: ./android/gradlew -p ./android :hello_sdl_android:test

    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Sdl JavaSE Tests
      run: ./javaSE/gradlew -p ./javaSE test

    - name: Hello Sdl JavaSE Tests
      run: ./hello_sdl_java/gradlew -p ./hello_sdl_java test

    - name: Sdl JavaEE Tests
      run: ./javaEE/gradlew -p ./javaEE test
